### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kabasakalis** [sassanh/nvim-cm-eclim#1] opened 2017-10-07 13:21 UTC
I have installed eclim successfully,  (I get ping from neoVim) but plugin does not work.
I just installed your plugin with no additional configuration.
Do I need a special configuration for NCM ?  Here is my NCM configuration:

let g:cm_smart_enable=1  
let g:cm_auto_popup = 0 
imap  <silent>  <Tab> <Plug> (cm_force_refresh)

inoremap <silent> <expr> <CR>  (pumvisible() ?  "\<c-y>\<Plug>(expand_or_nl)" : "\<CR>")
inoremap <silent> <expr> <Plug>(expand_or_nl) (cm#completed_is_snippet() ? "\<C-t>" : "\<CR>")

**Comment by sassanh** [comment] 2017-10-07 18:57
Please enable nvim-cm logs and share the logs here.

**Comment by sassanh** [comment] 2017-10-07 18:59
See "Trouble shooting" section of ncm vim-docs.

**Comment by drumaddict** [comment] 2017-10-07 20:48
I enabled the logs but no log file was generated. I don't have the patience for this. Thanks for trying to help, I guess you can close the issue.

**Comment by sassanh** [comment] 2017-10-07 21:25
I'm sorry it didn't work for you. I keep it open in case you (or someone with similar problem) find the time to find out what's the issue is.

**Comment by drumaddict** [comment] 2017-10-07 23:31
I managed to get a log. I am attaching the log file. The error is around line 95. I was trying to autocomplete `System.out` and `import java.` 
[log.txt](https://github.com/sassanh/nvim-cm-eclim/files/1366512/log.txt)

**Comment by sassanh** [comment] 2017-10-07 23:47
Thanks. Now I see what's the problem. You should create a project. Eclim uses an other workspace than your eclipse's workspace. Easiest thing to do is to run eclipse with the workspace Eclim uses. Create/Import your project there, and then you should be able to use it.
I suggest you follow the eclim's documentation to setup eclim (pinging is not enough) then you should be able to use this plugin.
Easiest thing to do to make sure eclim is setup correctly is to try to use its own vim plugin and try to autocomplete with it. Then you can disable it and use ncm and enjoy the async auto completion.

**Comment by drumaddict** [comment] 2017-10-08 13:29
Thanks, I got it working!
Well I should have taken a look at [eclim Getting Started Tutorial](http://eclim.org/gettingstarted.html).
I think you should include some basic instructions in README file.
Installing Eclipse has a small gotcha  : you have to click the menu triple bar in the installer, go to advanced mode and disable Bundle Pool before installing. Otherwise eclim installation will fail.

Having gone through all this pain, I am somewhat worried about using NeoVim for Java development.
I have read many comments in threads where people say it's a very bad idea, if not impossible for 
bigger projects. I come from Ruby On Rails,which has no build system or no need for a visual debugger.
Things get trickier with compiled languages like C++ or Java. Maybe It would be better to use  an IDE with a vim plugin, I won't be able to configure every little vim detail but I will have all the advantages of a modern IDE like debugging plus more. What do you think?

![image](https://user-images.githubusercontent.com/323951/31317219-c077402a-ac45-11e7-9f1a-be20ed77536f.png)

**Comment by sassanh** [comment] 2017-10-08 14:21
It's somehow personal decision. For me it's really hard to work in an editor other than vim (currently neovim) I don't have problems building my project thanks to gradle for Java and Makefiles for C++. You can keep another terminal tab / tmux screen / internal neovim terminal (based on your personal preferences) open to run `gradle` or `make`. You can also use some plugins designed to run `gradle` and `make` async inside vim. But thanks to NCM and ALE you have quality async auto completion and linter in vim and usually it's easy to find the syntax highlighter and indent manager for your programming language for vim.

Usually it's easy to setup vim for your programming language but if it's not that easy I prefer to suffer a little pain setting up vim instead of suffering a lot of pain dealing with an graphical IDE and needing to use mouse or memorizing bunch of new shortcuts. But as I said it's a personal decision.

Btw, can we close this issue?

**Comment by drumaddict** [comment] 2017-10-08 19:10
I have been using NeoVim for the last two years and I understand the benefits. I even coded my last 2 C++ projects in NeoVim, (with CMake as a build tool), it went smooth. I used command line debugging tool, gdb and Valgrind for memory profiling, but then I switched to QtCreator IDE and was amazed how these tools were integrated in the GUI offering a much more convenient experience than the command line. 

I already use tmux, I can switch to NeoVim and the command line in microseconds, great tool. I also use ALE with NCM.

Last, before you close the issue, can I have your vim configuration for java stuff? It could save me some time. For example, what do you use for debugging? And what about better syntax highlighting, I'm not satisfied with the current one, do you have any configurations for that? 
Thanks in advance and excuse my verbosity!

**Comment by sassanh** [comment] 2017-10-08 19:28
It's not that much, vim is not an operating system like emacs. All I expect from vim other than its intuitive editing capabilities is syntax highlighting, auto completion (with inline documentation if possible), indentation and lint. I also have `tfnico/vim-gradle` but I rarely use it and prefer to have another terminal tab to run gradle. I'm working on a libgdx project and it's in its early stage.

**Comment by drumaddict** [comment] 2017-10-09 11:23
One last question, did you manage to set up [debugging](http://eclim.org/vim/java/debug.html)  with eclim ?
To debug one has to start vim with `--servername` option but NeoVim has no such option. Do you use some other tool/plugin for debugging? Thanks in advance!

**Comment by sassanh** [comment] 2017-10-09 11:45
Unfortunately I don't think it's easy to set up debugging with eclim (I didn't even try). The client/serevr feature is supposed to come with Neovim .3: https://github.com/neovim/neovim/issues/1750

**Comment by sassanh** [comment] 2018-09-19 22:28
@kabasakalis I just remembered you said you're using Qt Creator. I developed a plugin for Qt Creator that runs a real instance of Neovim in background and by doing so it brings all your vim plugins, configs, etc to QtCreator, it runs your init.vim. Considering that you're a user of Qt Creator and Neovim I thought maybe you'd like to try it, this is the repository: https://github.com/sassanh/qnvim
It has some problems I described in the Readme.md but it works alright for me.

**Comment by kabasakalis** [comment] 2018-09-23 06:45
@sassanh Long time no see! Thanks for your interest.
I now use neovim only for real quick edits. I have switched to Jetbrains editors for Java and C++. There is this IdeaVim plugin which brings Vim into the editors, and it gives you the convenience to configure the keybindings as you like with a `.ideavimrc` file. You can map editor functions to Vim keybindings which is really powerful. There's nothing I did in Neovim that I can't do in Jetbrains editors now.

**Comment by sassanh** [comment] 2018-09-23 13:44
@kabasakalis I'm glad you found a way to have vim functionality in your editor, I guess IdeaVim doesn't support plugins though. Maybe someone will provide neovim backend for Jetbrains and people can use their own vimrc in Jetbrains too.

**Closed by sassanh** 2018-09-23 13:44 UTC
